on: [push]
name: build
jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Determine Docker image tag and name
        id: determine_tag
        run: |
          ref="${GITHUB_REF##*/}"
          echo "::set-output name=ref::$(echo $ref)"
          echo "::set-output name=image_full::$(echo ghcr.io/${GITHUB_REPOSITORY}:$ref)"
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Build docker image
        run: docker build -t ${{ steps.determine_tag.outputs.image_full }} .
        working-directory: ./app  
      - name: Push docker image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ilyamochalov --password-stdin
          docker push ${{ steps.determine_tag.outputs.image_full }}